/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bbc7c2c4-3b94-40a5-8f5c-9fd2783fed48",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_h171P0rvN",
    "aws_user_pools_web_client_id": "1ap932k1j0k65r7khjffqesfp3",
    "oauth": {}
};


export default awsmobile;
